config/routes.rb
Rails.application.routes.draw do
  resources :file_uploaders
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/file_uploader.rb
class FileUploader < ApplicationRecord
    has_many_attached :data_file
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/file_uploaders_controller.rb
class FileUploadersController < ApplicationController
  before_action :set_file_uploader, only: [:show, :edit, :update, :destroy]

  # GET /file_uploaders
  # GET /file_uploaders.json
  def index
    @file_uploaders = FileUploader.all
  end

  # GET /file_uploaders/1
  # GET /file_uploaders/1.json
  def show
  end

  # GET /file_uploaders/new
  def new
    @file_uploader = FileUploader.new
    
  end

  # GET /file_uploaders/1/edit
  def edit
  end

  # POST /file_uploaders
  # POST /file_uploaders.json
  def create
    @file_uploader = FileUploader.new(file_uploader_params)

    respond_to do |format|
      if @file_uploader.save
        format.html { redirect_to @file_uploader, notice: 'File uploader was successfully created.' }
        format.json { render :show, status: :created, location: @file_uploader }
      else
        format.html { render :new }
        format.json { render json: @file_uploader.errors, status: :unprocessable_entity }
      end
    end
    
    FileUploader.last.data_file.each do |file|
      run_script(file.blob.key, file.filename)
    end
  end

  # PATCH/PUT /file_uploaders/1
  # PATCH/PUT /file_uploaders/1.json
  def update
    respond_to do |format|
      if @file_uploader.update(file_uploader_params)
        format.html { redirect_to @file_uploader, notice: 'File uploader was successfully updated.' }
        format.json { render :show, status: :ok, location: @file_uploader }
      else
        format.html { render :edit }
        format.json { render json: @file_uploader.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /file_uploaders/1
  # DELETE /file_uploaders/1.json
  def destroy
    @file_uploader.destroy
    respond_to do |format|
      format.html { redirect_to file_uploaders_url, notice: 'File uploader was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

    def run_script(file_name, name)
     
      path = "./storage/#{file_name[0,2]}/#{file_name[2,2]}/#{file_name}"
      
      puts "the path is #{path}"
      puts "starting transfer"

      `./lib/scripts/transfer.sh #{path} rails_upload_#{name}`
      puts $?
      puts "file uploaded"
    end
    
    # Use callbacks to share common setup or constraints between actions.
    def set_file_uploader
      @file_uploader = FileUploader.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def file_uploader_params
      params.require(:file_uploader).permit(data_file: [])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/file_uploaders_helper.rb
module FileUploadersHelper
end

app/views/file_uploaders/_form.html.erb
<%= form_with(model: @file_uploader, local: true) do |form| %>
  <% if @file_uploader.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@file_uploader.errors.count, "error") %> prohibited this file_uploader from being saved:</h2>

      <ul>
        <% @file_uploader.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.file_field :data_file, multiple: true,  class: 'form-control'%>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/file_uploaders/edit.html.erb
<h1>Editing File Uploader</h1>

<%= render 'form', file_uploader: @file_uploader %>

<%= link_to 'Show', @file_uploader %> |
<%= link_to 'Back', file_uploaders_path %>

app/views/file_uploaders/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Uploaded Files</h1>

<table class="table table-borderless table-striped">
  <thead>
    <tr>
      <th scope="col" colspan="1">file name</th>
      <th scope="col" colspan="3">options</th>
    </tr>
  </thead>

  <tbody>
    <% @file_uploaders.each do |file_uploader| %>
      <tr>

        <td>
        <% file_uploader.data_file.each do |file|%>
          <span class="file-name"><%= file.filename %></span>
        <% end %>
        </td>
        <td>
          <%= link_to 'Show', file_uploader, :method=>"get" %>
        </td>
        <td><%= link_to 'Edit', edit_file_uploader_path(file_uploader), :method=>"get" %></td>
        <td><%= link_to 'Destroy', file_uploader, method: :delete, data: { confirm: 'Are you sure?' }%></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= button_to 'New File Uploader', new_file_uploader_path, :method=>"get", class:"btn btn-primary" %>

app/views/file_uploaders/new.html.erb
<h1>Upload Files</h1>


<%= render 'form', post: @file_uploader %>


<%= button_to 'Back', file_uploaders_path, :method=>"get", class:"btn btn-primary" %>

app/views/file_uploaders/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_file_uploader_path(@file_uploader) %> |
<%= link_to 'Back', file_uploaders_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>UploadFIles</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="//fonts.googleapis.com/css?family=Open+Sans" />
  </head>

  <body>
    <nav class="navbar navbar-expand-md navbar-dark bg-dark">
        <a class="navbar-brand" href="#">Data Lake Sample!</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExample04" aria-controls="navbarsExample04" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarsExample04">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="/file_uploaders/">Uploaded Files</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="/file_uploaders/new">Upload File</a>
            </li>
          </ul>

      </div>
    </nav>

    <div class="main-body">
      <%= yield %>
    </div>
    
  </body>

  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</html>